const http = require('http');
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');

const ROOT = path.resolve(__dirname, '..');
const PORT = 8927;
const TARGETS = process.argv.slice(2).length ? process.argv.slice(2) : ['about-xinhua.html', 'dividend-xinhua.html'];
const VIEWPORTS = [{name:'390', width:390, height:844}, {name:'430', width:430, height:844}, {name:'1440', width:1440, height:900}];
const REQUIRED = {
  'about-xinhua.html': ['新华保险是一家什么样的公司？','中央汇金到底是干什么的','新华投资能力'],
  'dividend-xinhua.html': ['新华的分红，到底怎么样？','红利实现率怎么看','盈满鑫身故保障']
};
function startServer(){
  const server=http.createServer((req,res)=>{const rel=decodeURIComponent((req.url||'/').split('?')[0]);const file=path.resolve(ROOT,'.'+(rel==='/'?'/index.html':rel));if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found');}const ext=path.extname(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.json':'application/json','.css':'text/css'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});return new Promise(resolve=>server.listen(PORT,'127.0.0.1',()=>resolve(server)));}
(async()=>{const server=await startServer();let failed=0;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--no-sandbox']});try{for(const file of TARGETS){if(!fs.existsSync(path.join(ROOT,file))){console.log(`FAIL ${file}: file missing`);failed++;continue;}for(const vp of VIEWPORTS){const page=await browser.newPage({viewport:{width:vp.width,height:vp.height},deviceScaleFactor:1});const consoleErrors=[],pageErrors=[],failedRequests=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>pageErrors.push(String(e)));page.on('requestfailed',r=>failedRequests.push(`${r.url()} :: ${r.failure()?.errorText||'failed'}`));const response=await page.goto(`http://127.0.0.1:${PORT}/${file}`,{waitUntil:'networkidle',timeout:30000});const result=await page.evaluate(()=>{const nav=new Set([...document.querySelectorAll('.nav')]);const overflow=[...document.querySelectorAll('body *')].filter(el=>{if(nav.has(el)||el.closest('.nav')||el.classList.contains('header'))return false;const cs=getComputedStyle(el);if(cs.textOverflow==='ellipsis')return false;return el.scrollWidth>el.clientWidth+2&&cs.overflowX!=='auto'&&cs.overflowX!=='scroll';}).slice(0,12).map(el=>({tag:el.tagName,cls:el.className||'',scrollWidth:el.scrollWidth,clientWidth:el.clientWidth}));return{docWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth,viewport:innerWidth,overflow};});const text=await page.locator('body').innerText();const missing=(REQUIRED[file]||[]).filter(t=>!text.includes(t));const problems=[];if(!response||response.status()>=400)problems.push(`HTTP ${response&&response.status()}`);if(result.docWidth>result.viewport+2||result.bodyWidth>result.viewport+2)problems.push(`page overflow ${result.docWidth}/${result.bodyWidth}`);if(result.overflow.length)problems.push(`content overflow ${JSON.stringify(result.overflow)}`);if(missing.length)problems.push(`missing text: ${missing.join(',')}`);if(consoleErrors.length)problems.push(`console ${consoleErrors.length}`);if(pageErrors.length)problems.push(`pageerror ${pageErrors.length}`);if(failedRequests.length)problems.push(`failed resources ${failedRequests.length}`);const status=problems.length?'FAIL':'PASS';if(problems.length)failed++;console.log(`${status} ${file} ${vp.name}px | overflow=${result.docWidth-result.viewport} | console=${consoleErrors.length} | pageerror=${pageErrors.length} | resources=${failedRequests.length}${problems.length?' | '+problems.join(' ; '):''}`);await page.close();}}}finally{await browser.close();server.close();}process.exitCode=failed?1:0;})();


